#!/usr/bin/env bash

# Check if an IP address is provided as an argument
#Script that pings another address enterd over 5 times
if [ "$1" ]
then
ping -c 5 "$1"
else
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
