#!/usr/bin/env bash

# Function to handle SIGTERM and SIGQUIT signals
function terminate_handler {
    echo "I hate the kill command"
    echo "Y U no love me?!"
    rm -f /var/run/myscript.pid
    exit 0
}

# Function to handle SIGINT signal
function interrupt_handler {
    echo "Y U no love me?!"
}

# Trap SIGTERM, SIGINT, and SIGQUIT signals and execute the corresponding functions
trap terminate_handler SIGTERM SIGQUIT
trap interrupt_handler SIGINT

# Get the PID of the current process and save it to the file /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
